name: physicsgpt
description: AI-powered Physics Solver built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.2.2
  flutter_dotenv: ^5.2.1

  # UI
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  intl: ^0.20.2

  # Markdown + Math
  flutter_markdown: ^0.7.3

  # Storage
  shared_preferences: ^2.5.3
  markdown: ^7.3.0
  flutter_math_fork: ^0.7.4

  # Image & PDF
  image_picker: ^1.2.3
  file_picker: ^10.3.2
  syncfusion_flutter_pdf: ^31.1.17

  # Local Storage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Sharing
  share_plus: ^11.1.0

  # Permissions
  permission_handler: ^12.0.1

  # Icons
  flutter_svg: ^2.2.0

  # Animations
  lottie: ^3.3.1
  flutter_highlight: ^0.7.0
  uuid: ^4.5.1
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/images/